/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package banksystem;

/**
 *
 * @author Administrator
 */
public class BankSystem {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    BankDAO dao = new BankDAO();
        
        System.out.println("--- TESTING AUTO-INCREMENT SETUP ---");
        
        // Test Data
        String accID = "4567"; // Your manual 4-digit ID
        String fName = "Autoo";
        String lName = "Incremenyt";
        String email = "auwto@test.com";
        String phone = "09990002122";
        String type = "Savings";
        double bal = 2000.00;

        System.out.println("Attempting to save Account: " + accID);
        System.out.println("Customer ID will be generated by MySQL...");

        // Try to save using the DAO method
        // Note: Make sure your DAO saveNewAccount is the version using LAST_INSERT_ID()
        boolean success = dao.saveNewAccount(accID, fName, lName, email, phone, type, bal);

        if (success) {
            System.out.println("SUCCESS! Account and Customer created.");
            System.out.println("Check your DB: SELECT * FROM customer;");
            System.out.println("Notice how customer_id was filled automatically.");
        } else {
            System.out.println("FAILED!");
            System.out.println("Possible reasons:");
            System.out.println("1. Account ID " + accID + " already exists.");
            System.out.println("2. The 'AI' box is NOT checked in MySQL Workbench for customer_id.");
            System.out.println("3. Column names don't match (phone vs phone_number).");
        }
    }
    }

    

